CREATE DATABASE IF NOT EXISTS cifrado;

USE cifrado;

CREATE TABLE IF NOT EXISTS mensajes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    palabra VARCHAR(30) NOT NULL,
    cifrado VARCHAR(30) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);